menu:
  Home: /
  Event Details: /eventdetails/
  Tickets: /tickets/
  Sponsorship Opportunities: /sponsorship/
  Sponsors: /sponsors/
  Volunteer: /volunteer/

favicon: /css/images/favicon.ico